-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 11:54:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pre-TPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pre-TPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pre-TPI` DEFAULT CHARACTER SET utf8 ;
USE `pre-TPI` ;

-- -----------------------------------------------------
-- Table `pre-TPI`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pre-TPI`.`restaurants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zipcode` SMALLINT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Uniquerestaurant` (`name` ASC, `address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pre-TPI`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pre-TPI`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Uniquecategory` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pre-TPI`.`meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pre-TPI`.`meals` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` SMALLINT(4) UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `price` SMALLINT(4) UNSIGNED NOT NULL,
  `kcal/100g` TINYINT(4) UNSIGNED NOT NULL,
  `carbohydrates/100g` SMALLINT(3) UNSIGNED NOT NULL,
  `lipids/100g` SMALLINT(3) UNSIGNED NOT NULL,
  `proteins/100g` SMALLINT(3) UNSIGNED NOT NULL,
  `ingredients` TEXT NOT NULL,
  `restaurants_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_meals_restaurants1_idx` (`restaurants_id` ASC) VISIBLE,
  UNIQUE INDEX `Uniquemeal` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_meals_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `pre-TPI`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pre-TPI`.`restaurants_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pre-TPI`.`restaurants_has_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurants_id` INT UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  INDEX `fk_restaurants_has_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_restaurants_has_categories_restaurants_idx` (`restaurants_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_restaurants_has_categories_restaurants`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `pre-TPI`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `pre-TPI`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
